### ISSUE TITLE
Units selection has no default when first viewed

### ISSUE THREAD

**Issue by OperationXen** [mikeyhogarth/cocktails#117]
Option setting "units" has no default, and so when viewing the app for the first time all measurements are given as "undefined" - ie; 

4.5 undefined of vodka
2 undefined of gin
9 undefined of orange juice

**Comment by OperationXen** [comment]
Looks like the cause is that the radiogroup is missing the property "defaultValue='parts'"

**Comment by mikeyhogarth** [comment]
Cheers I'll take a look :)

**Comment by mikeyhogarth** [comment]
Okay closing as can't recreate and neither can @OperationXen _ I think what's happened here is that once upon a time the state looked a certain way - @OperationXen visited, I then changed it and when he visited the client just pulled his old, erroneous state out and started using it. As this is just a pet project I think we can get away with it since the bug is proven to self-heal.
