### ISSUE TITLE
Setting up for Docker

### ISSUE THREAD

**Issue by consolecwby** [mikeyhogarth/cocktails#128]
I am currently working on getting a dockerfile wrote for your webapp.

**Comment by mikeyhogarth** [comment]
Okay sure - is that just for local development to avoid having to install node?

**Comment by consolecwby** [comment]
Yeah I prefer to deploy all my stuff in containers so its easier to manage. But i hit a roadblock so its going to take some time. 
Here is the dockerfile i made. 
[Dockerfile.txt](https://github.com/mikeyhogarth/cocktails/files/6442631/Dockerfile.txt)
But i get this error in the logs

```
(node:7) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/app/src/index.js:1
import React from "react";
^^^^^^
SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:355:18)
    at wrapSafe (node:internal/modules/cjs/loader:1038:15)
    at Module._compile (node:internal/modules/cjs/loader:1072:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Function.Module._load (node:internal/modules/cjs/loader:828:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47

```

Ill keep working to figure it out just wanted to post my current status.

**Comment by mikeyhogarth** [comment]
So the reason that error is happening is because you're using the `node:latest` image and this is not a node app, so it's getting confused when it sees things like `import` (which is not supported by `node.js`) so you need to cater for that somehow - see the guide here: 
https://mherman.org/blog/dockerizing-a-react-app/

I would understand doing all this if this was to help running it locally (so it means you don't need to install node to run it) but I am curious what benefits of paying for container hosting over using services like Netlify for free? Where do you host stuff? I've always been confused about people who use docker for frontends and think I must be missing something!

**Comment by mikeyhogarth** [comment]
We don't need docker
